// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcRGgJh1R4O5TJCudtsnnTdaD9UVNPb0',
    appId: '1:530730794831:web:30fbf71a346a3f69e18f3a',
    messagingSenderId: '530730794831',
    projectId: 'demenapp-46d28',
    authDomain: 'demenapp-46d28.firebaseapp.com',
    storageBucket: 'demenapp-46d28.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzpCA2t3n11t8hMlhOu8VRc0PhST-m5lI',
    appId: '1:530730794831:android:50c20d55dbc79c90e18f3a',
    messagingSenderId: '530730794831',
    projectId: 'demenapp-46d28',
    storageBucket: 'demenapp-46d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2eiUEPM8YAcN2jg6JVeRYtwNY8mo2OkM',
    appId: '1:530730794831:ios:c8b40675fb1ee624e18f3a',
    messagingSenderId: '530730794831',
    projectId: 'demenapp-46d28',
    storageBucket: 'demenapp-46d28.firebasestorage.app',
    iosBundleId: 'com.example.deduraApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2eiUEPM8YAcN2jg6JVeRYtwNY8mo2OkM',
    appId: '1:530730794831:ios:c8b40675fb1ee624e18f3a',
    messagingSenderId: '530730794831',
    projectId: 'demenapp-46d28',
    storageBucket: 'demenapp-46d28.firebasestorage.app',
    iosBundleId: 'com.example.deduraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUcRGgJh1R4O5TJCudtsnnTdaD9UVNPb0',
    appId: '1:530730794831:web:30fbf71a346a3f69e18f3a',
    messagingSenderId: '530730794831',
    projectId: 'demenapp-46d28',
    authDomain: 'demenapp-46d28.firebaseapp.com',
    storageBucket: 'demenapp-46d28.firebasestorage.app',
  );
}
